### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by cjihrig** [danielcardoso/html-pages#2]
Hello,

The Node.js ecosystem security team has received a report regarding this module. Previously, an email was sent to npm@danielcardoso.net, but no response was received. What is the best way to privately reach someone with commit rights to this repo? Feel free to reach out to me directly via the email address listed in my GitHub profile.

Thanks!

**Comment by danielcardoso** [comment]
Sorry for the delay...
In the meanwhile I fixed some security issues.

If the problems persists please reach me via npm@danielcardoso.net. I forward all emails to my personal email.
